01_button
js-tasks-ru/htmlcss-20220120_denis37 pull request #3
Opened 2022-02-06 14:07 UTC by AngelKeeper

2022-02-06 14:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-07 08:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-07 21:15 UTC, GSemikozov requested changes

2022-02-07 21:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    min-width: 200px;
в принципе, это можно вообще убрать)

2022-02-07 21:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
лучше pointer-events: none

2022-02-08 07:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-08 07:56 UTC, AngelKeeper commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
поменял

2022-02-08 07:56 UTC, AngelKeeper commented on 03-lection1/01-button/button.css
> +    min-width: 200px;
убрал

2022-02-08 12:42 UTC, GSemikozov approved these changes

2022-02-08 12:42 UTC, merged